-- Migration: Add Email Intake System
-- Date: November 6, 2025
-- Description: Tables for custom domain email intake with AI classification

-- Email intake configuration per organization
CREATE TABLE IF NOT EXISTS email_intake_channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  email_address VARCHAR(255) NOT NULL,
  inbound_identifier VARCHAR(100) NOT NULL UNIQUE,
  
  -- DNS verification status
  mx_verified BOOLEAN DEFAULT FALSE,
  spf_verified BOOLEAN DEFAULT FALSE,
  dkim_verified BOOLEAN DEFAULT FALSE,
  verified_at TIMESTAMP,
  
  -- DKIM keys (generated by Resend)
  dkim_public_key_1 TEXT,
  dkim_public_key_2 TEXT,
  
  -- Auto-create rules
  auto_create_mode VARCHAR(20) DEFAULT 'ai_decide', -- 'tickets', 'quotes', 'ai_decide'
  require_human_review BOOLEAN DEFAULT TRUE,
  confidence_threshold DECIMAL(3,2) DEFAULT 0.70,
  
  -- Status
  is_active BOOLEAN DEFAULT FALSE,
  last_email_received_at TIMESTAMP,
  
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT unique_org_email UNIQUE(organisation_id, email_address)
);

-- Email intake activity log
CREATE TABLE IF NOT EXISTS email_intake_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  channel_id UUID REFERENCES email_intake_channels(id) ON DELETE SET NULL,
  
  -- Email details
  from_address VARCHAR(255),
  to_address VARCHAR(255),
  subject TEXT,
  body_text TEXT,
  body_html TEXT,
  attachments_count INTEGER DEFAULT 0,
  
  -- AI processing
  ai_intent VARCHAR(50),
  ai_confidence DECIMAL(3,2),
  ai_extracted_entities JSONB,
  ai_model VARCHAR(50),
  ai_processing_time_ms INTEGER,
  
  -- Action taken
  action_taken VARCHAR(50),
  work_item_id UUID,
  work_item_type VARCHAR(20),
  
  -- Auto-reply
  auto_reply_sent BOOLEAN DEFAULT FALSE,
  auto_reply_sent_at TIMESTAMP,
  
  -- Status
  requires_review BOOLEAN DEFAULT FALSE,
  reviewed_by UUID REFERENCES users(id),
  reviewed_at TIMESTAMP,
  
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_email_intake_channels_org ON email_intake_channels(organisation_id);
CREATE INDEX IF NOT EXISTS idx_email_intake_channels_identifier ON email_intake_channels(inbound_identifier);
CREATE INDEX IF NOT EXISTS idx_email_intake_channels_active ON email_intake_channels(is_active) WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_email_intake_logs_org ON email_intake_logs(organisation_id);
CREATE INDEX IF NOT EXISTS idx_email_intake_logs_channel ON email_intake_logs(channel_id);
CREATE INDEX IF NOT EXISTS idx_email_intake_logs_created ON email_intake_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_intake_logs_review ON email_intake_logs(requires_review) WHERE requires_review = TRUE;

-- Add comment
COMMENT ON TABLE email_intake_channels IS 'Email intake configuration for custom domain email addresses';
COMMENT ON TABLE email_intake_logs IS 'Activity log for all incoming emails processed by the intake system';
